name: Sync to Backend Repo

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout neumo-api
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout backend repo
        uses: actions/checkout@v4
        with:
          repository: arnoldchrisoduor1/Backend-Deployments
          token: ${{ secrets.BACKEND_REPO_TOKEN }}
          path: backend-repo

      - name: Copy FastAPI code to backend repo
        run: |
          # Remove old fastapi-service directory if it exists
          rm -rf backend-repo/fastapi-service
          
          # Copy current code (excluding .git folder)
          rsync -av neumo-api/ backend-repo/fastapi-service/

      - name: Commit and push to backend repo
        run: |
          cd backend-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-sync FastAPI code from neumo-api" || exit 0
          git push